# Generated by Django 3.2.2 on 2024-01-13 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_remove_passwords_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
